// Labelled interviewer scripts for the Auto Answer live rig.
//
// Each interviewer turn says what SHOULD happen:
//   expect 'answer' — an answer must appear, once, for this ask (q = the ask);
//   expect 'silent' — nothing may fire;
//   expect 'either' — logistics / comprehension checks where both are defensible.
// `parts` interleaves spoken text with { pause } gaps, so announced structures
// and thinking pauses reach the STT with real silences inside the turn.
// `check` is a loose content check; answers are still hand-read.
// `after: 'firstToken'` speaks the turn that long after the PREVIOUS answer's
// first token, i.e. while that answer is still streaming.

export const technicalInterview = [
  { who: 'interviewer', id: 'T01', expect: 'either', parts: ['Hi there, thanks for making the time today. Can you hear me okay?'] },
  { who: 'user', text: 'Yes, I can hear you fine, thanks for having me.' },
  { who: 'interviewer', id: 'T02', expect: 'silent', parts: ["Great. So I'm Sarah, I lead the platform team here. We'll spend about forty five minutes today. A few questions about your background, then some fundamentals, and then a coding problem."] },
  { who: 'user', text: 'Sounds good.' },
  { who: 'interviewer', id: 'T03', expect: 'answer', q: 'Tell me a little bit about yourself and what you have been working on recently', check: /\w{4,}.*\w{4,}/s,
    parts: ["Let's start with you. Tell me a little bit about yourself and what you've been working on recently."] },
  { who: 'user', text: "Sure. I'm a backend engineer. For the last three years I've been building payment services in Go and Node." },
  { who: 'interviewer', id: 'T04', expect: 'answer', q: "What's the difference between a process and a thread", check: /memory|address space/i,
    parts: ["Nice. What's the difference between a process and a thread?"] },
  { who: 'user', text: 'A process has its own memory space, and threads share memory inside one process.' },
  { who: 'interviewer', id: 'T05', expect: 'answer', q: 'And when would you pick one over the other', check: /isolat|crash|shar|overhead|parallel|CPU|communicat/i,
    parts: ['Right. And when would you pick one over the other'] },
  { who: 'user', text: 'Processes when I want isolation, threads when the work shares a lot of state.' },
  { who: 'interviewer', id: 'T06', expect: 'answer', q: 'How does a hash map handle collisions', check: /chain|open addressing|prob|bucket|linked/i,
    parts: ['Okay. How does a hash map handle collisions'] },
  { who: 'user', text: 'Usually with chaining, or with open addressing and probing.' },
  { who: 'interviewer', id: 'T07', expect: 'answer', q: 'how would you design a distributed cache for a read heavy service', check: /consistent hash|shard|replica|evict|TTL|LRU|invalidat/i,
    parts: ["Why do we use consistent hashing? Because adding a node shouldn't reshuffle every key. So with that in mind, how would you design a distributed cache for a read heavy service?"] },
  { who: 'user', text: "I'd shard keys with consistent hashing, keep replicas for the hot keys, and use a time to live with LRU eviction." },
  { who: 'interviewer', id: 'T08', expect: 'answer', q: 'design a data structure that supports insert, remove and get random in average constant time',
    check: /(array|list)[\s\S]*(hash|map|dict)|(hash|map|dict)[\s\S]*(array|list)/i,
    parts: ["Alright, let's move on to coding.", { pause: 1500 },
      'I want you to design a data structure that supports three operations.', { pause: 1400 },
      'First, insert a value.', { pause: 1200 },
      'Second, remove a value.', { pause: 1200 },
      'And third, get a random element, where every element has the same probability of being returned.', { pause: 700 },
      'All three should run in average constant time.'] },
  { who: 'interviewer', id: 'T09', expect: 'silent', parts: ["Take your time, and feel free to use whatever language you're comfortable with."] },
  { who: 'user', text: "Thanks. I'll use Python. I'm thinking a list for the values, plus a dictionary from each value to its index in the list." },
  { who: 'interviewer', id: 'T10', expect: 'answer', q: "What's the time complexity of your remove operation, and why", check: /O\(1\)|constant/i,
    parts: ["What's the time complexity of your remove operation, and why?"] },
  { who: 'user', text: "It's constant, because I swap with the last element and pop." },
  { who: 'interviewer', id: 'T11', expect: 'either', parts: ["So you're swapping the element with the last one and then popping it, right?"] },
  { who: 'user', text: 'Exactly.' },
  { who: 'interviewer', id: 'T12', expect: 'answer', q: 'walk me through what happens when you type a URL into the browser and press enter', check: /DNS[\s\S]*(TCP|TLS|HTTP)/i,
    parts: ["Let's switch gears. Can you walk me through what happens when you type a URL into the browser and press enter?"] },
  { who: 'user', text: 'The browser resolves the name with DNS, opens a TCP and TLS connection, and sends the HTTP request.' },
  { who: 'interviewer', id: 'T13', expect: 'silent', parts: ["Good. We'll come back to the networking side a bit later."] },
  { who: 'interviewer', id: 'T14', expect: 'answer', q: 'Tell me about a time you disagreed with a teammate on a technical decision, and how you resolved it', check: /\w{4,}.*\w{4,}/s,
    parts: ['Tell me about a time you disagreed with a teammate on a technical decision, and how you resolved it.'] },
  { who: 'user', text: 'We disagreed about moving to an event queue. I wrote a small prototype and we compared the numbers together.' },
  { who: 'interviewer', id: 'T15', expect: 'answer', q: 'a Node service in production is slowly running out of memory, how would you go about debugging that', check: /heap|snapshot|inspect|profil|clinic|leak/i,
    parts: ['Hmm, let me think how to phrase this next one.', { pause: 1600 },
      'Say a Node service in production is slowly running out of memory over a few days.', { pause: 900 },
      'How would you go about debugging that?'] },
  { who: 'interviewer', id: 'T16', expect: 'answer', after: 'firstToken', delayMs: 1500, q: 'Why not just restart it on a schedule', check: /mask|root cause|symptom|band|hide|hiding|underlying/i,
    parts: ['Why not just restart it on a schedule?'] },
  { who: 'user', text: 'Restarting hides the leak. I would rather find the root cause with heap snapshots.' },
  { who: 'interviewer', id: 'T17', expect: 'answer', q: 'Do you have any questions for me', check: /\?/,
    parts: ["Okay, we're almost at time. Do you have any questions for me?"] },
  { who: 'user', text: 'Yes. What does on call look like for the platform team?' },
  { who: 'interviewer', id: 'T18', expect: 'silent', parts: ['Good question. We run a weekly rotation with a secondary, and most pages are about deploys.'] },
  { who: 'interviewer', id: 'T19', expect: 'silent', parts: ["Thanks so much for your time today. We'll be in touch soon."] },
];

// Looking for work: a recruiter screen. Personal and logistics questions, a
// lot of recruiter monologue (company pitch, process) that must stay quiet,
// and short asks without a question mark.
export const lookingForWork = [
  { who: 'interviewer', id: 'L01', expect: 'either', parts: ["Hi, this is Priya from the talent team at Northwind. Is now still a good time to talk?"] },
  { who: 'user', text: "Yes, now works great, thanks for calling." },
  { who: 'interviewer', id: 'L02', expect: 'silent', parts: ["Perfect. So just to give you some context, Northwind builds logistics software for mid size retailers. We're about two hundred people, fully remote, and this role sits on the integrations team."] },
  { who: 'interviewer', id: 'L03', expect: 'answer', q: 'walk me through your background', check: /\w{4,}.*\w{4,}/s,
    parts: ["To start, could you walk me through your background and what you're doing today?"] },
  { who: 'user', text: "Sure. I'm a backend engineer at a fintech startup. I've been there three years, mostly on payment integrations in Go and Node." },
  { who: 'interviewer', id: 'L04', expect: 'answer', q: 'what made you start looking', check: /\w{4,}.*\w{4,}/s,
    parts: ['Great. And what made you start looking for something new'] },
  { who: 'user', text: "I want to work on a bigger platform, and our team is being folded into another group." },
  { who: 'interviewer', id: 'L05', expect: 'answer', q: 'what are your salary expectations for this role', check: /\d|range|flexib|compens|total/i,
    parts: ["Makes sense. I have to ask this one early. What are your salary expectations for this role?"] },
  { who: 'user', text: "I'm targeting around one hundred and forty to one hundred and sixty thousand base, but I'm flexible for the right role." },
  { who: 'interviewer', id: 'L06', expect: 'silent', parts: ["Okay, that's within our band for this level, so no concerns there."] },
  { who: 'interviewer', id: 'L07', expect: 'answer', q: "What's your notice period", check: /week|notice|month|start/i,
    parts: ["And what's your notice period with your current employer?"] },
  { who: 'user', text: "It's four weeks." },
  { who: 'interviewer', id: 'L08', expect: 'answer', q: 'Tell me about a project you are really proud of', check: /\w{4,}.*\w{4,}/s,
    parts: ["Tell me about a project you're really proud of."] },
  { who: 'user', text: "I led a rewrite of our payout service. It cut failed payouts by half." },
  { who: 'interviewer', id: 'L09', expect: 'answer', q: 'Why Northwind', check: /\w{4,}.*\w{4,}/s,
    parts: ["That's impressive. So why Northwind, what drew you to us specifically?"] },
  { who: 'user', text: "Logistics is a hard integration problem, and the remote culture is a big plus for me." },
  { who: 'interviewer', id: 'L10', expect: 'silent', parts: ["So here's how the process works. There's a technical screen with an engineer, then a system design round, and then a final conversation with the hiring manager. The whole thing usually takes about three weeks."] },
  { who: 'interviewer', id: 'L11', expect: 'answer', q: 'are you interviewing anywhere else right now', check: /\w{4,}/,
    parts: ['Are you interviewing anywhere else at the moment'] },
  { who: 'user', text: "Yes, I'm in early stages with two other companies." },
  { who: 'interviewer', id: 'L12', expect: 'silent', parts: ["Thanks for being upfront. I'll send over a calendar invite for the technical screen later today."] },
  { who: 'interviewer', id: 'L13', expect: 'answer', q: 'Do you have any questions for me about the role or the team', check: /\?/,
    parts: ['Before we wrap up, do you have any questions for me about the role or the team?'] },
  { who: 'user', text: 'What does the integrations team work on day to day?' },
  { who: 'interviewer', id: 'L14', expect: 'silent', parts: ["Mostly building and maintaining connectors to carriers and warehouse systems. It's a lot of API work and a fair amount of on call."] },
  { who: 'interviewer', id: 'L15', expect: 'silent', parts: ["Great talking with you. Have a good rest of your day."] },
];

// Sales discovery call: the "interviewer" channel is the PROSPECT. Objections
// and buying questions must fire; the prospect describing their own setup,
// and small talk, must not.
export const salesCall = [
  { who: 'interviewer', id: 'S01', expect: 'silent', parts: ["Hey, thanks for jumping on. Sorry I'm a couple of minutes late, my last meeting ran over."] },
  { who: 'user', text: 'No worries at all. Thanks for making the time.' },
  { who: 'interviewer', id: 'S02', expect: 'silent', parts: ["So a bit of background on us. We're a team of about forty support agents, and right now we use a mix of spreadsheets and a shared inbox to track escalations."] },
  { who: 'interviewer', id: 'S03', expect: 'answer', q: 'how does your product handle escalations between tiers', check: /\w{4,}.*\w{4,}/s,
    parts: ['So how does your product actually handle escalations between tiers?'] },
  { who: 'user', text: 'Each ticket carries its tier, and escalation rules move it up automatically with the full history attached.' },
  { who: 'interviewer', id: 'S04', expect: 'answer', q: 'Does it integrate with Zendesk', check: /zendesk|integrat|api|connector/i,
    parts: ['Okay. Does it integrate with Zendesk'] },
  { who: 'user', text: 'Yes, there is a native Zendesk connector that syncs both ways.' },
  { who: 'interviewer', id: 'S05', expect: 'answer', q: 'what does pricing look like for a team our size', check: /\w{4,}.*\w{4,}/s,
    parts: ["Good. And what does pricing look like for a team our size?"] },
  { who: 'user', text: "For forty seats you'd be on our team plan. I can send the exact numbers after the call." },
  { who: 'interviewer', id: 'S06', expect: 'answer', q: 'that seems expensive compared to what we pay now, why is it worth it', check: /\w{4,}.*\w{4,}/s,
    parts: ["Honestly that seems expensive compared to what we pay now. Why would it be worth it for us?"] },
  { who: 'user', text: 'Mostly time saved on manual routing, and fewer escalations that fall through the cracks.' },
  { who: 'interviewer', id: 'S07', expect: 'silent', parts: ["Right. Our biggest pain is that escalations get lost over the weekend, when only two people are on shift."] },
  { who: 'interviewer', id: 'S08', expect: 'answer', q: 'how do you handle data security and are you SOC 2 compliant', check: /SOC|secur|encrypt|complian/i,
    parts: ['What about data security? Are you SOC two compliant?'] },
  { who: 'user', text: 'We are SOC two type two, and data is encrypted at rest and in transit.' },
  { who: 'interviewer', id: 'S09', expect: 'silent', parts: ["Okay, I'll need to loop in our IT lead on that before we go further."] },
  { who: 'interviewer', id: 'S10', expect: 'answer', q: 'what would the next steps look like if we wanted to try it', check: /\w{4,}.*\w{4,}/s,
    parts: ['If we wanted to try it, what would the next steps look like?'] },
  { who: 'user', text: 'I can set up a two week pilot with your escalations team.' },
  { who: 'interviewer', id: 'S11', expect: 'silent', parts: ["Sounds good. Send me the details and I'll share them with the team. Thanks again."] },
];

export const SCRIPTS = { ti: technicalInterview, lfw: lookingForWork, sales: salesCall };
