import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { LlmProvider, ProviderError, SttProvider } from '../../../dist-electron/electron/defence/providers.js';

async function mockServer(handler){const server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;return{url:`http://127.0.0.1:${port}/v1`,close:()=>new Promise(resolve=>server.close(resolve))}}
test('mock STT multipart and LLM structured response pass schema validation',async t=>{const mock=await mockServer((req,res)=>{if(req.url.endsWith('/audio/transcriptions')){let size=0;req.on('data',chunk=>size+=chunk.length);req.on('end',()=>{assert.ok(size>20);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({text:'How does retrieval work?'}))})}else{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({spokenAnswer:'Ready.',noEvidence:true,keywords:[],followUps:[]})}}]}))}});t.after(()=>mock.close());
  const stt=new SttProvider({provider:'mock',apiKey:'TEST',baseUrl:mock.url,model:'mock-stt',language:'auto',timeoutMs:2000,maxRetries:0});const sttResult=await stt.transcribeWithMetrics(Buffer.from('RIFF fixture wave bytes'),'audio/wav');assert.match(sttResult.value,/retrieval/);assert.equal(sttResult.timing.status,200);
  const llm=new LlmProvider({provider:'mock',apiKey:'TEST',baseUrl:mock.url,model:'mock-llm',timeoutMs:2000,maxRetries:0});const llmResult=await llm.answerWithMetrics('question',[],[],'en','brief');assert.equal(llmResult.value.spokenAnswer,'Ready.');assert.equal(llmResult.value.noEvidence,true);
});
test('provider authentication errors are classified without leaking response bodies',async t=>{const mock=await mockServer((_req,res)=>{res.writeHead(401,{'Content-Type':'text/plain'});res.end('secret internal provider details')});t.after(()=>mock.close());const stt=new SttProvider({provider:'mock',apiKey:'TEST',baseUrl:mock.url,model:'mock',language:'auto',timeoutMs:1000,maxRetries:0});await assert.rejects(()=>stt.transcribe(Buffer.from('audio'),'audio/wav'),error=>error instanceof ProviderError&&error.code==='AUTHENTICATION_FAILED'&&!error.message.includes('internal provider'))});
test('provider payment errors are classified without exposing response bodies',async t=>{const mock=await mockServer((_req,res)=>{res.writeHead(402,{'Content-Type':'text/plain'});res.end('private billing details')});t.after(()=>mock.close());const llm=new LlmProvider({provider:'mock',apiKey:'TEST',baseUrl:mock.url,model:'mock',timeoutMs:1000,maxRetries:0,thinking:false});await assert.rejects(()=>llm.answer('question',[],[],'en','brief'),error=>error instanceof ProviderError&&error.code==='PAYMENT_OR_BALANCE_REQUIRED'&&!error.message.includes('billing'))});

test('STT auto omits language while explicit zh/en and audio extensions are preserved',async t=>{const bodies=[];const mock=await mockServer((req,res)=>{const chunks=[];req.on('data',chunk=>chunks.push(chunk));req.on('end',()=>{bodies.push(Buffer.concat(chunks).toString('latin1'));res.writeHead(200,{'Content-Type':'application/json','x-groq-request-id':'groq-test'});res.end(JSON.stringify({text:'CBA Top-K player-season'}))})});t.after(()=>mock.close());const base={provider:'openai-compatible',apiKey:'TEST',baseUrl:mock.url,model:'whisper-large-v3-turbo',timeoutMs:2000,maxRetries:0};await new SttProvider({...base,language:'auto'}).transcribe(Buffer.from('audio'),'audio/mp4');await new SttProvider({...base,language:'zh'}).transcribe(Buffer.from('audio'),'audio/webm');await new SttProvider({...base,language:'en'}).transcribe(Buffer.from('audio'),'audio/wav');assert.doesNotMatch(bodies[0],/name="language"/);assert.match(bodies[1],/name="language"[\s\S]*zh/);assert.match(bodies[2],/name="language"[\s\S]*en/);assert.match(bodies[0],/filename="speech\.m4a"/);assert.match(bodies[1],/filename="speech\.webm"/);assert.match(bodies[2],/filename="speech\.wav"/)});

test('DeepSeek request uses v4 flash JSON mode, disables thinking, and repairs structured output once with stable evidence IDs',async t=>{const requests=[];const mock=await mockServer((req,res)=>{const chunks=[];req.on('data',chunk=>chunks.push(chunk));req.on('end',()=>{requests.push(JSON.parse(Buffer.concat(chunks).toString('utf8')));const content=requests.length===1?'not json':JSON.stringify({spokenAnswer:'Grounded.',noEvidence:false,keywords:[],followUps:[]});res.writeHead(200,{'Content-Type':'application/json','x-request-id':`deepseek-${requests.length}`});res.end(JSON.stringify({id:`response-${requests.length}`,choices:[{message:{content}}]}))})});t.after(()=>mock.close());const provider=new LlmProvider({provider:'openai-compatible',apiKey:'TEST',baseUrl:mock.url.replace(/\/v1$/,''),model:'deepseek-v4-flash',timeoutMs:2000,maxRetries:0,thinking:false});const evidence=[{sourceType:'project',path:'README.md',lineStart:1,lineEnd:2,excerpt:'Top-K shortlist evidence',status:'IMPLEMENTED',score:1}];const result=await provider.answerWithMetrics('Why Top-K?',evidence,[],'en','brief');assert.equal(result.value.spokenAnswer,'Grounded.');assert.equal(requests.length,2);for(const body of requests){assert.equal(body.model,'deepseek-v4-flash');assert.deepEqual(body.response_format,{type:'json_object'});assert.deepEqual(body.thinking,{type:'disabled'});assert.match(body.messages[1].content,/"id":1/);assert.match(body.messages[1].content,/spokenAnswer in English and questionExplanation in Chinese/)}assert.equal(result.timing.retries,1)});
